kind: BuildConfig
apiVersion: v1
metadata:
  name: demo-rest-pipeline
spec:
  source:
    git:
      uri: https://github.com/dsanchor/demo-cicd
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/Jenkinsfile
      env:
        - name: JENKINS_PROJECT
          value: cicd
        - name: CICD_GIT_URL
          value: https://github.com/niranjantj/demo-cicd
        - name: APP_GIT_URL
          value: https://github.com/niranjantj/demo-rest
        - name: APP_TEMPLATE
          value: openshift/templates/demo-rest-template.yml
        - name: APP_NAME
          value: demo-rest
#        - name: CUSTOM_TEMPLATE_PARAMETERS
#          value: "-p YOUR_PARAM1=x p YOUR_PARAM2=y"
        - name: IMAGESTREAM_PROJECT
          value: development
        - name: DEV_PROJECT
          value: development
        - name: TEST_PROJECT
          value: test
        - name: TEST_TAG
          value: test
        - name: PROD_PROJECT
          value: production
        - name: PROD_TAG
          value: production
        - name: SONAR_URL
          value: http://sonarqube-cicd.139.59.78.16.nip.io
        - name: NEXUS_URL
#          value: http://nexus-cicd.139.59.78.16.nip.io/
          value: http://nexus-cicd.139.59.78.16.nip.io/
        - name: NEXUS_RELEASE_REPOSITORY
          value: /nexus/content/repositories/releases
        - name: POSTMAN_TESTS_COLLECTION
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/demo-rest.postman_collection.json"
        - name: POSTMAN_DEV_ENVIRONMENT_CONFIG
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/environments/development.postman_environment.json"
        - name: POSTMAN_TEST_ENVIRONMENT_CONFIG
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/environments/test.postman_environment.json"
        - name: POSTMAN_ALTPROD_ENVIRONMENT_CONFIG
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/environments/production-alternate.postman_environment.json"
        - name: POSTMAN_PROD_ENVIRONMENT_CONFIG
          value: "https://raw.githubusercontent.com/dsanchor/demo-rest/master/openshift/tests/environments/production.postman_environment.json"


